Use long command line options

diff --git a/libffado.SlackBuild b/libffado.SlackBuild
--- a/libffado.SlackBuild
+++ b/libffado.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # Slackware build script for FFADO
-# Copyright (C) 2010-2020 Georgi D. Sotirov <gdsotirov@gmail.com>
+# Copyright (C) 2010-2022 Georgi D. Sotirov <gdsotirov@gmail.com>
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -38,12 +38,12 @@ TMP=${TMP:-/tmp}
 CWD=${CWD:-`pwd`}
 
 if [ ! -e $TMP ]; then
-  mkdir -p $TMP # location to build the source
+  mkdir --parents $TMP # location to build the source
 fi
 
 SRC=$TMP/$NAME-${VERSION}
 if [ -e $SRC -a -d $SRC ]; then
-  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  echo "Source directory '$SRC' already exists! Please, move it or remove it."
   exit 1
 fi
 
@@ -52,16 +52,17 @@ if [ -e $PKG -a -d $PKG ]; then
   echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
   exit 2
 fi
-mkdir -p $PKG
+mkdir --parents $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/$NAME-${VERSION}.tar.?z* || exit 3
-cd $SRC fix_source
+tar --extract --verbose --file=$CWD/$NAME-${VERSION}.tgz || exit 3
+cd $SRC
+fix_source
 
 # Apply patches
 if [ -e $CWD/$NAME-$VERSION.diff ]; then
-  patch -p1 -b -z.orig < $CWD/$NAME-$VERSION.diff || exit 4
+  patch --backup --strip=1 --suffix=.orig < $CWD/$NAME-$VERSION.diff || exit 4
 fi
 
 # build fails without the proper LibXML++ cflags
@@ -76,13 +77,15 @@ scons \
   LIBDIR=/usr/lib${LIBDIRSUFFIX} \
   SERIALIZE_USE_EXPAT=yes \
   DESTDIR=$PKG install \
-  -j4 || exit 5
+  --jobs 4 || exit 5
 
 # Additional installation steps
-install -m 755 -d -D $PKG/usr/share/applications
-install -m 644 $SRC/support/xdg/ffado.org-ffadomixer.desktop $PKG/usr/share/applications/ffadomixer.desktop
-install -m 755 -d -D $PKG/usr/share/icons/hicolor/64x64/apps
-install -m 644 $SRC/support/xdg/hi64-apps-ffado.png          $PKG/usr/share/icons/hicolor/64x64/apps/ffado.png
+install --mode 755 --directory $PKG/usr/share/applications
+install --mode 644 $SRC/support/xdg/ffado.org-ffadomixer.desktop \
+        $PKG/usr/share/applications/ffadomixer.desktop
+install --mode 755 --directory $PKG/usr/share/icons/hicolor/64x64/apps
+install --mode 644 $SRC/support/xdg/hi64-apps-ffado.png \
+        $PKG/usr/share/icons/hicolor/64x64/apps/ffado.png
 
 # Prepare
 bin_perms $PKG
@@ -90,32 +93,32 @@ bin_perms $PKG
 DOCFILES="$DOCFILES LICENSE.*"
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
 ( cd $PKG/usr/doc/$NAME-$VERSION
-  install -m 644 LICENSE.GPLv2 COPYING )
+  install --mode 644 LICENSE.GPLv2 COPYING )
 gzip_man $PKG
 
 mkdir -p $PKG/install
-install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
-install -m 644 $CWD/slack-required $PKG/install/slack-required
+install --mode 644 $CWD/slack-desc     $PKG/install/slack-desc
+install --mode 644 $CWD/slack-required $PKG/install/slack-required
 
 SBDIR=$PKG/usr/src/slackbuilds/$NAME-$VERSION
-mkdir -p $SBDIR
-install -m 644 $CWD/slack-desc          $SBDIR/slack-desc
-install -m 644 $CWD/slack-required      $SBDIR/slack-required
+install --mode 755 --directory $SBDIR
+install --mode 644 $CWD/slack-desc          $SBDIR/slack-desc
+install --mode 644 $CWD/slack-required      $SBDIR/slack-required
 if [ -e $CWD/$NAME-$VERSION.diff ]; then
-  install -m 644 $CWD/$NAME-$VERSION.diff $SBDIR/$NAME-$VERSION.diff
+install --mode 644 $CWD/$NAME-$VERSION.diff $SBDIR/$NAME-$VERSION.diff
 fi
-install -m 644 $CWD/$NAME.SlackBuild    $SBDIR/$NAME.SlackBuild
+install --mode 644 $CWD/$NAME.SlackBuild    $SBDIR/$NAME.SlackBuild
 
 # Assemble package
 cd $PKG
-PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
-makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
-cd $PKG_DIR
-md5sum $PKGNAME.txz > $PKGNAME.txz.md5
-cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
+PKGNAME=${NAME}-${VERSION}-${ARCH}-${BUILD}${MYIN}
+makepkg --chown n --linkadd y $PKG_DIR/${PKGNAME}.txz
+md5sum $PKG_DIR/${PKGNAME}.txz > $PKG_DIR/${PKGNAME}.txz.md5
+install --mode 644 $PKG/install/slack-desc $PKG_DIR/${PKGNAME}.txt
 
+# Cleanup (optionally)
 if [ "$1" == "--cleanup" ]; then
-  rm -r $SRC
-  rm -r $PKG
+  rm --recursive $SRC
+  rm --recursive $PKG
 fi
 
